### ISSUE TITLE
패키지 정리

### ISSUE THREAD

**Issue by gabang2** [whatever-mentoring/Dopamine_Backend#42]
# Issue
- config파일이 여러 패키지에 흩어져있어 패키지가 너무 많아 보기가 어려운 것 같습니다.
![image](https://github.com/whatever-mentoring/Dopamine_Backend/assets/82714785/84e4a20f-3212-4d82-a539-6eda53ca3c12)
=> 여기서 config파일을 하나의 패키지에 관리하고,
=> Entity들은 domain이란 패키지 안에 관리를 하면 좋을 것 같습니다.

# 예상되는 패키지 구조
- config - JwtConfig.java / WebConfig.java ...
- domain - challenge
                - member
                - level
                - ...

@KarmaPol 이렇게 바꾸려고 하는데 의견 부탁드립니다.

**Comment by KarmaPol** [comment]
config 모아둘 필요성을 느낀 참이었는데 좋습니다!
